
                server_config_path = "server_0.json"
                host = "localhost"
                port = 9000
                internal_host = "localhost"
                internal_port = 10000
                metrics_host = "localhost"
                metrics_port = 11000
                external_protocol = { Grpc = "ClearText" }
                internal_protocol = { Grpc = "ClearText" }
            

                [[shards]]
                host = "localhost"
                port = 9001
                metrics_host = "localhost"
                metrics_port = 11001
                